spring.application.name=E-Commerce

spring.datasource.url=jdbc:mysql://localhost:3306/Ecommerce
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretkey=fdadfjk2232#@#$!@$#@Ffddac#@$cq32cdskj